### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by rsodre** [cartridge-gg/docs#11]
found some broken links in these pages...

https://docs.cartridge.gg/controller/configuration
* `Session Options`
* `Theme Options`

https://docs.cartridge.gg/controller/inventory
* `torii-config/public-tokens/mainnet.tom`

https://docs.cartridge.gg/controller/achievements/creation
* See also `AchievableComponent`

https://docs.cartridge.gg/controller/achievements/progression
* See also `AchievableComponent`

**Comment by tarrencev** [comment]
Thanks! Pushed a fix for these
